### ISSUE TITLE
cmake test error

### ISSUE THREAD

**Issue by wwood** [BioPP/bpp-seq#1]
Hi,

I'm attempting to package `bpp-seq` for GNU Guix, and I came across an test failure in `test_io`. The problem was that it could not find the example data e.g. `example.fasta`, because this doesn't get copied to the build directory.

Is it possible to fix this somehow? Or is there some particular way I should be running the tests?
Thanks,
ben

**Comment by jydu** [comment]
Hi, 

The unit tests are currently designed to be run using CTest. Each test corresponds to one executable, located in the test directory, where the input files are also located. Running the program from that directory should work. This is a known issue however, are we're planning to remove dependencies to external files in the next release.

Julien.

**Comment by wwood** [comment]
Hi,

Thanks for the reply. As it turns out the problem was simple to solve, just by not running an out-of-source build. I'm not sure if this issue should be closed or not, I'll leave that to you.
