### ISSUE TITLE
DNA / RNA Alphabet values

### ISSUE THREAD

**Issue by PrometheusABW** [BioPP/bpp-seq#10]
I actually use version 2.3.2 of bpp-seq and found following behaviour.
``
alpha = new bpp::RNA(); //bpp::NucleicAlphabet

   for (auto i = 0; i < alpha->getNumberOfStates(); i++){
       std::cout << i << '\t' << alpha->intToChar(i) << std::endl;
   }
``

returns no error until i= 15 which I think is a bug

0	A
1	C
2	G
3	U
4	M
5	R
6	W
7	S
8	Y
9	K
10	V
11	H
12	D
13	B
14	N
ERROR! AlphabetException: BadIntException: 15. AbstractAlphabet::getState(int): Specified base unknown(RNA)

For DNA it's the same issue

**Comment by jydu** [comment]
Hi,

You'd rather use getNumberOfTypes() instead. In nucleotides alphabets, characters N, X, ?, O and 0 are all coded as 14 (unresolved character). The number of "Types" (int) is therefore 15, while the number of supported characters is 19. 

Hope this helps,

Julien.

**Comment by PrometheusABW** [comment]
Hi,
Oh had never thought of that much unresolved chars in D/RNA  alpha... however that clears
thanks!
