### ISSUE TITLE
question about bpp-seq install 

### ISSUE THREAD

**Issue by dumicola** [BioPP/bpp-seq#15]
Dear Developers,

I'm having some problems compiling bio-seq. After I finished compiling bpp-core, I got an error compiling bio-seq directly. The following error message is displayed.

/ local/include/Bpp/Numeric Table. H: 1059:19: error: 'make_unique' is not a member of 'STD'
dt = std::make_unique&lt;  Table&lt; T&gt;  &gt; (0, nCol);

/ local/include/Bpp/Numeric Table. H: 1059:19: note: suggested the alternative: '__unique'
dt = std::make_unique&lt;  Table&lt; T&gt;  &gt; (0, nCol);
__unique

/ local/include/Bpp/Numeric Table. H: 1059-41: error: expected primary - expression before '& gt; 'token
dt = std::make_unique&lt;  Table&lt; T&gt;  &gt; (0, nCol);
...

Some of the solutions were to change -std=c++11 to -std=c++14 in CMakeLists, but then the error was reported again. I compiled according to the documentation. I don't know if there are any other operation problems that cause compilation errors.**

/bpp-seq/test/test_probseq.cpp:163:60: error: cannot convert 'std::unique_ptr&lt; bpp::Table&lt; double&gt; , std::default_delete&lt; bpp::Table&lt; double&gt;  &gt;  &gt; 'to' DataTable* {aka bpp::Table&lt; double&gt; *} 'in initialization

DataTable * data = DataTable::read(iss, false, " ", false);

/bpp-seq/test/test_probseq.cpp: 29:65: error: cannot convert 'std::unique_ptr&lt; bpp::Table&lt; double&gt; , std::default_delete&lt; bpp::Table&lt; double&gt;  &gt;  &gt; 'to' DataTable* {aka bpp::Table&lt; double&gt; *} 'in initialization

DataTable * dna_data = DataTable::read(isss, false, " ", false);

Thanks

**Comment by lgueguen** [comment]
Dear user,

I doubt your version is up to date. For example, now in test_probseq at lines 163 & 263, there is an "auto" type instead of DataTable* .

Cheers,
Laurent
